services:
  nginx:
    image: nginx:1.25.3
    ports:
      - 80:80
    volumes:
      - ./docker/webserver/conf/:/etc/nginx/
#    depends_on:
#      - frontend
#  frontend:
#    image: node:16.17-slim
#    user: "node"
#    working_dir: /home/node/app
#    environment:
#      - NODE_ENV=development
#    volumes:
#      - ./my-club-web/:/home/node/app
#    expose:
#      - "3000"
#    command: "npm start"
