import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import { Task } from '../model/task'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const[tasks, setTasks] = useState<Task[]>([]);

  useEffect(()=>{
    // TODO fix cors
    // fetch("http://localhost:8080/tasks")
    // .then(res => res.json())
    // .then((apiTasks:Task[]) => {
    //   setTasks(apiTasks)
    // })
  },[])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Your Space!
        </h1>

        <p className={styles.description}>
          {tasks.map((task:Task,index: number)=>{
            return (
              <div key={"task-" + index}>
                <label htmlFor={"task-" + task.name + "-" + index}>{task.name}</label>
                <input id={"task-" + task.name + "-" + index} type="checkbox" checked={task.done} />
              </div>
            )
          })}
        </p>

      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}

export default Home
